### ISSUE TITLE
Custom partition scheme?

### ISSUE THREAD

**Issue by dominic-p** [davidmytton/alpine-linux-headless-raspberrypi#2]
First, thank you so much for this. I have been looking for a good way to test Alpine on my Pi 4 cluster, and this is working great!

The problem I'm running into is that, by default, `setup-alpine` repartitions the boot drive and creates 2 partitions (a small boot partitions, and then rest for the system). This is a sensible default, but in my case, I want to reserve maybe 40G for the main system and leave the rest of my disk in a 3rd partition for use by ceph/rook (rook requires a raw, unformatted partition).

I tried skipping the disk setup part at the end of the `setup-alpine` script and then mounting the root and boot partitions on /mnt and running `setup-disk /mnt`. That appeared to work, but the Pi failed to come back up after reboot. It's a headless system, so I wasn't able to see what the output was.

As I'm writing this, it feels more like a support request than an issue. Sorry about that. Feel free to ignore this, and I'll post back if I find the solution. Otherwise, thanks again for putting this together.

**Comment by davidmytton** [comment]
I'm only documenting the steps here so can't help with this one unfortunately. I suggest checking out IRC or the mailing list links from https://alpinelinux.org/community/

Feel free to comment if you find a solution though.

**Comment by dominic-p** [comment]
Thanks for the tips. I appreciate it.

I was able to get it to work! The trick was to move the mount point of the first (boot) partition to /mnt/boot and then remount it as rw (I think it was mounted read only by default and that's why it was failing). 

So, in a nutshell:

- mount root partition on /mnt
- mkdir /mnt/boot
- mount -o move /media/sda1 /mnt/boot
- mount -o remount,rw /mnt/boot
- setup-disk -m sys /mnt
- chmod -x /mnt/etc/local.d/headless.start (otherwise any changes to /etc/network/interfaces get overwritten on boot)
- make any other changes to /mnt/etc (hosts, network, etc)
- reboot
